language: python
script: python -m unittest discover
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
